[book]
authors = [""]
language = "en"
src = "specs"
title = "World Chain Specs"


[preprocessor.mermaid]
command = "mdbook-mermaid"

[output.html]
additional-js = [
    "specs/static/mermaid.min.js",
    "specs/static/mermaid-init.js",
    "specs/static/solidity-min.js",
]
