[package]
name = "flashblocks-rpc"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
# internal
flashblocks-primitives.workspace = true

# reth
reth.workspace = true
reth-chainspec.workspace = true
reth-provider.workspace = true
reth-primitives.workspace = true
reth-transaction-pool.workspace = true
reth-evm.workspace = true
reth-node-api.workspace = true
reth-rpc-eth-api.workspace = true
reth-rpc-eth-types.workspace = true
reth-storage-api.workspace = true
reth-node-builder.workspace = true
reth-tasks.workspace = true
reth-chain-state.workspace = true

# op-reth
reth-optimism-rpc.workspace = true
reth-optimism-forks.workspace = true
reth-optimism-primitives.workspace = true
reth-optimism-evm.workspace = true
reth-optimism-flashblocks.workspace = true

# alloy
alloy-primitives.workspace = true
alloy-eips.workspace = true
alloy-consensus.workspace = true
alloy-rpc-types-engine.workspace = true

op-alloy-rpc-types.workspace = true
op-alloy-network.workspace = true
op-alloy-rpc-types-engine.workspace = true

# tokio
tokio.workspace = true

# misc
tracing.workspace = true
jsonrpsee-core.workspace = true
jsonrpsee.workspace = true
eyre.workspace = true
