[package]
name = "world-chain-builder-payload"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true

[lints]
workspace = true

[dependencies]
# Internal
flashblocks-builder.workspace = true
world-chain-pool.workspace = true
world-chain-rpc.workspace = true

# reth
reth.workspace = true
reth-basic-payload-builder.workspace = true
reth-chain-state.workspace = true
reth-evm.workspace = true
reth-optimism-node.workspace = true
reth-optimism-chainspec.workspace = true
reth-optimism-payload-builder.workspace = true
reth-optimism-primitives.workspace = true
reth-optimism-forks.workspace = true
reth-provider.workspace = true
reth-primitives.workspace = true
reth-transaction-pool.workspace = true
reth-primitives-traits.workspace = true
reth-payload-util.workspace = true

# revm
revm.workspace = true
revm-primitives.workspace = true

# alloy
alloy-network.workspace = true
alloy-signer-local.workspace = true
alloy-consensus.workspace = true
alloy-eips.workspace = true
alloy-rpc-types-debug.workspace = true
op-alloy-rpc-types.workspace = true
alloy-rlp.workspace = true

# misc
eyre.workspace = true
tracing.workspace = true
derive_more.workspace = true
semaphore-rs.workspace = true

[dev-dependencies]
tokio.workspace = true
alloy-sol-types.workspace = true
alloy-signer-local.workspace = true
alloy-signer.workspace = true
alloy-network.workspace = true
