[package]
name = "world-chain-builder-pool"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true

[dependencies]
world-chain-builder-pbh.workspace = true

reth.workspace = true
reth-db.workspace = true
reth-optimism-node.workspace = true
reth-primitives.workspace = true
reth-provider.workspace = true
reth-eth-wire-types.workspace = true
reth-e2e-test-utils = { workspace = true, optional = true }
reth-trie-db = { workspace = true, optional = true }
reth-trie = { workspace = true, optional = true }
reth-stages-types = { workspace = true, optional = true }
reth-optimism-primitives.workspace = true
reth-optimism-chainspec.workspace = true
revm-primitives.workspace = true
reth-primitives-traits.workspace = true
reth-optimism-forks.workspace = true

alloy-genesis.workspace = true
alloy-consensus.workspace = true
alloy-primitives.workspace = true
alloy-rpc-types.workspace = true
alloy-eips.workspace = true
alloy-sol-types.workspace = true
alloy-rlp.workspace = true
alloy-signer-local = { workspace = true, optional = true }
alloy-network = { workspace = true, optional = true }
op-alloy-consensus.workspace = true

# 3rd party
ethers-core.workspace = true
tokio.workspace = true
semaphore.workspace = true
eyre.workspace = true
thiserror.workspace = true
tracing.workspace = true
parking_lot.workspace = true
bon = { workspace = true, optional = true }
rayon.workspace = true

[dev-dependencies]
test-case.workspace = true
alloy-signer-local.workspace = true
reth-e2e-test-utils.workspace = true
chrono.workspace = true

[features]
default = []
test = [
    "dep:reth-e2e-test-utils",
    "dep:reth-trie-db",
    "dep:reth-stages-types",
    "dep:reth-trie",
    "dep:alloy-signer-local",
    "dep:alloy-network",
    "dep:bon",
]

[lints]
workspace = true
